name: Build Android APK

on:
  push:
    branches: [ main ] # Roda toda vez que você der push na main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Web Assets
        run: |
          mkdir -p www
          # Tenta copiar os arquivos da raiz. 
          # Se não achar na raiz, ele tenta buscar em qualquer subpasta (exceto node_modules e android)
          find . -name "index.html" -not -path "./node_modules/*" -not -path "./android/*" -exec cp {} www/ \;
          find . -name "calc.js" -not -path "./node_modules/*" -not -path "./android/*" -exec cp {} www/ \;
          find . -name "style.css" -not -path "./node_modules/*" -not -path "./android/*" -exec cp {} www/ \;
          
          echo "Arquivos movidos para a pasta www:"
          ls www

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        run: |
          npx cap copy android
          npx cap update android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk